import type { CriarProcessoInput, TransicionarProcessoInput, ListarProcessosGenericosQuery } from "./processos-genericos.schema.js";
export declare class DirecaoNaoEncontradaError extends Error {
}
export declare function criarProcessoGenerico(params: {
    municipioId: string;
    requerenteUtilizadorId: string;
    input: CriarProcessoInput;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function adicionarAnexoProcesso(params: {
    municipioId: string;
    processoId: string;
    nomeFicheiro: string;
    storageKey: string;
    utilizadorUploadId: string;
    tipoDocumentoCodigo?: string;
    exigirRequerente?: boolean;
    tipoAnexo?: "ENTRADA" | "SAIDA";
    origemInterna?: boolean;
}): Promise<{
    id: string;
    criadoEm: Date;
    storageKey: string;
    processoId: string;
    nomeFicheiro: string;
    versao: number;
    tipoDocumentoCodigo: string | null;
    tipoAnexo: import("../../generated/prisma/index.js").$Enums.TipoAnexoProcesso;
    utilizadorUploadId: string | null;
}>;
export declare function listarDocumentosEmFaltaProcesso(params: {
    municipioId: string;
    processoId: string;
}): Promise<import("../../config/catalogo-servicos.js").DocumentoExigido[]>;
export declare function transicionarProcessoGenerico(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    input: TransicionarProcessoInput;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function listarProcessosGenericos(params: {
    municipioId: string;
    executorId: string;
    query: ListarProcessosGenericosQuery;
}): Promise<{
    items: {
        id: string;
        criadoEm: Date;
        alteradoEm: Date;
        tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
        estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
        numero: string;
        origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
        assunto: string;
        requerenteUtilizadorId: string | null;
        direcaoOrigemId: string | null;
        direcaoAtualId: string | null;
        direcaoDespachadaId: string | null;
        responsavelActualId: string | null;
        resultado: string | null;
        localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
        prazoLegalResposta: Date | null;
        diasAlertaAntesPrazo: number;
        alertaEnviadoEm: Date | null;
        escaladoEm: Date | null;
        arquivoDigitalEm: Date | null;
        arquivoMortoEm: Date | null;
        aguardaPagamento: boolean;
        servicoCodigo: string | null;
    }[];
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
}>;
export declare function obterProcessoGenericoInterno(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
    transicoes: {
        utilizador: {
            id: string;
            nomeCompleto: string;
        } | null;
        id: string;
        criadoEm: Date;
        estadoAnterior: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico | null;
        estadoNovo: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
        observacao: string | null;
        visivelAoCidadao: boolean;
    }[];
    anexos: {
        id: string;
        criadoEm: Date;
        nomeFicheiro: string;
        versao: number;
        utilizadorUpload: {
            id: string;
            nomeCompleto: string;
        } | null;
    }[];
}>;
export declare function obterTimelineCidadao(params: {
    municipioId: string;
    processoId: string;
    utilizadorId: string;
}): Promise<{
    timeline: {
        id: string;
        criadoEm: Date;
        estadoAnterior: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico | null;
        estadoNovo: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
        observacao: string | null;
    }[];
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function arquivarDigital(params: {
    municipioId: string;
    processoId: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function arquivarMorto(params: {
    municipioId: string;
    processoId: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function atribuirResponsavelProcesso(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    novoResponsavelActualId: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function apresentarAoAdministrador(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function despacharParaDireccao(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    direcaoDespachadaSigla: string;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function despacharParaAssessorJuridico(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    assessorUtilizadorId: string;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function expedirParaDireccao(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function subirResposta(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    viaExpediente: boolean;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function prepararSaida(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function submeterParaDespachoSaida(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function despacharSaida(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    autorizar: boolean;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
export declare function formalizarEnvioExterno(params: {
    municipioId: string;
    processoId: string;
    executorId: string;
    destinoExterno: string;
    observacao?: string;
}): Promise<{
    id: string;
    criadoEm: Date;
    alteradoEm: Date;
    tipo: import("../../generated/prisma/index.js").$Enums.TipoProcessoGenerico;
    estado: import("../../generated/prisma/index.js").$Enums.EstadoProcessoGenerico;
    numero: string;
    origem: import("../../generated/prisma/index.js").$Enums.OrigemProcessoGenerico;
    assunto: string;
    requerenteUtilizadorId: string | null;
    direcaoOrigemId: string | null;
    direcaoAtualId: string | null;
    direcaoDespachadaId: string | null;
    responsavelActualId: string | null;
    resultado: string | null;
    localizacaoActual: import("../../generated/prisma/index.js").$Enums.LocalizacaoProcesso;
    prazoLegalResposta: Date | null;
    diasAlertaAntesPrazo: number;
    alertaEnviadoEm: Date | null;
    escaladoEm: Date | null;
    arquivoDigitalEm: Date | null;
    arquivoMortoEm: Date | null;
    aguardaPagamento: boolean;
    servicoCodigo: string | null;
}>;
//# sourceMappingURL=processos-genericos.service.d.ts.map