export const TIPOS_CENTRO = ["ACOLHIMENTO_INFANTIL", "ACOLHIMENTO_IDOSOS", "COZINHA_SOCIAL", "MISTO", "OUTRO"] as const;
export const ESTADOS_CENTRO = ["ATIVO", "INATIVO", "EM_MANUTENCAO"] as const;

export const NIVEIS_RISCO_ZONA = ["BAIXO", "MEDIO", "ALTO"] as const;

export const TIPOS_CASO_SENSIVEL = ["VIOLENCIA_ABUSO", "SEM_REGISTO_CIVIL", "OUTRO"] as const;
export const ESTADOS_CASO_SENSIVEL = ["ABERTO", "EM_ACOMPANHAMENTO", "ENCAMINHADO", "ENCERRADO"] as const;
export const ACOES_AUDITORIA_CASO = ["VISUALIZACAO", "CRIACAO", "EDICAO", "ELIMINACAO", "RESTAURACAO"] as const;

export const TIPOS_PEDIDO_APOIO = ["MICROCREDITO", "HABITACAO", "APOIO_IDOSO", "CESTA_BASICA", "OUTRO"] as const;
export const ESTADOS_PEDIDO_APOIO = ["EM_ANALISE", "DEFERIDO", "INDEFERIDO", "CANCELADO"] as const;

export const TIPOS_PROGRAMA = ["EMPODERAMENTO_GENERO", "MICROCREDITO_COLETIVO", "OUTRO"] as const;
export const ESTADOS_PROGRAMA = ["ATIVO", "CONCLUIDO", "CANCELADO"] as const;
