export declare enum RoleType {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMINISTRADOR_MUNICIPAL = "ADMINISTRADOR_MUNICIPAL",
    ADMINISTRADOR_ADJUNTO_POLITICA = "ADMINISTRADOR_ADJUNTO_POLITICA",
    ADMINISTRADOR_ADJUNTO_ECONOMICA = "ADMINISTRADOR_ADJUNTO_ECONOMICA",
    ADMINISTRADOR_ADJUNTO_TECNICA = "ADMINISTRADOR_ADJUNTO_TECNICA",
    DIRECTOR_EDUCACAO = "DIRECTOR_EDUCACAO",
    DIRECTOR_SAUDE = "DIRECTOR_SAUDE",
    DIRECTOR_DESENVOLVIMENTO_ECONOMICO = "DIRECTOR_DESENVOLVIMENTO_ECONOMICO",
    DIRECTOR_AMBIENTE_SANEAMENTO = "DIRECTOR_AMBIENTE_SANEAMENTO",
    DIRECTOR_TRANSPORTES = "DIRECTOR_TRANSPORTES",
    DIRECTOR_ACCAO_SOCIAL = "DIRECTOR_ACCAO_SOCIAL",
    DIRECTOR_TURISMO_CULTURA = "DIRECTOR_TURISMO_CULTURA",
    DIRECTOR_TEMPOS_LIVRES = "DIRECTOR_TEMPOS_LIVRES",
    DIRECTOR_ENERGIA_AGUAS = "DIRECTOR_ENERGIA_AGUAS",
    DIRECTOR_INFRAESTRUTURAS = "DIRECTOR_INFRAESTRUTURAS",
    DIRECTOR_AGRICULTURA = "DIRECTOR_AGRICULTURA",
    DIRECTOR_REGISTOS = "DIRECTOR_REGISTOS",
    DIRECTOR_FISCALIZACAO = "DIRECTOR_FISCALIZACAO",
    CHEFE_DIRECÇÃO = "CHEFE_DIREC\u00C7\u00C3O",
    FUNCIONARIO_INTERNO = "FUNCIONARIO_INTERNO",
    CIDADAO = "CIDADAO",
    EMPRESA = "EMPRESA",
    INSTITUICAO = "INSTITUICAO",
    COMISSAO_MORADORES = "COMISSAO_MORADORES"
}
export declare enum Permission {
    CRIAR_UTILIZADOR = "CRIAR_UTILIZADOR",
    EDITAR_UTILIZADOR = "EDITAR_UTILIZADOR",
    ELIMINAR_UTILIZADOR = "ELIMINAR_UTILIZADOR",
    LISTAR_UTILIZADORES = "LISTAR_UTILIZADORES",
    VALIDAR_IDENTIDADE = "VALIDAR_IDENTIDADE",
    CRIAR_DIRECTOR = "CRIAR_DIRECTOR",
    EDITAR_DIRECTOR = "EDITAR_DIRECTOR",
    ELIMINAR_DIRECTOR = "ELIMINAR_DIRECTOR",
    LISTAR_DIRECTORES = "LISTAR_DIRECTORES",
    CRIAR_DOCUMENTO = "CRIAR_DOCUMENTO",
    EDITAR_DOCUMENTO = "EDITAR_DOCUMENTO",
    ELIMINAR_DOCUMENTO = "ELIMINAR_DOCUMENTO",
    CONSULTAR_DOCUMENTO = "CONSULTAR_DOCUMENTO",
    APROVAR_DOCUMENTO = "APROVAR_DOCUMENTO",
    REJEITAR_DOCUMENTO = "REJEITAR_DOCUMENTO",
    ASSINAR_DOCUMENTO = "ASSINAR_DOCUMENTO",
    SUBMETER_REQUERIMENTO = "SUBMETER_REQUERIMENTO",
    CONSULTAR_REQUERIMENTO = "CONSULTAR_REQUERIMENTO",
    ANALISAR_REQUERIMENTO = "ANALISAR_REQUERIMENTO",
    APROVAR_REQUERIMENTO = "APROVAR_REQUERIMENTO",
    CONSULTAR_LOGS_AUDITORIA = "CONSULTAR_LOGS_AUDITORIA",
    EXPORTAR_LOGS = "EXPORTAR_LOGS",
    CRIAR_RELATORIO = "CRIAR_RELATORIO",
    CONSULTAR_RELATORIO = "CONSULTAR_RELATORIO",
    EXPORTAR_RELATORIO = "EXPORTAR_RELATORIO",
    CONFIGURAR_SISTEMA = "CONFIGURAR_SISTEMA",
    GERIR_DIREÇÕES = "GERIR_DIRE\u00C7\u00D5ES",
    GERIR_ROLES = "GERIR_ROLES",
    GERIR_PERMISSOES = "GERIR_PERMISSOES",
    ENVIAR_NOTIFICACAO = "ENVIAR_NOTIFICACAO"
}
export declare const RBAC_MATRIX: Record<RoleType, Permission[]>;
export declare function temPermissao(role: RoleType, permissao: Permission): boolean;
export declare function obterPermissoes(role: RoleType): Permission[];
export declare function ehAdmin(role: RoleType): boolean;
export declare function ehDirector(role: RoleType): boolean;
export declare function ehPublico(role: RoleType): boolean;
export declare const PERFIS_QUE_EXIGEM_DUPLA_APROVACAO: string[];
//# sourceMappingURL=rbac_matrix.d.ts.map